In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a.sum()

21

In [4]:
np.sum(a)

21

In [5]:
>>> a = np.arange(10)**3
>>> a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [7]:
a[2]  # indexing

8

In [8]:
a[2:5]  # slicing

array([ 8, 27, 64], dtype=int32)

In [9]:
b = np.array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [14]:
b[2][2]  # list-style

22

In [15]:
b[2, 2]  # numpy-style

22

In [20]:
b[1:4, 1:3]

array([[11, 12],
       [21, 22],
       [31, 32]])

In [22]:
a = np.array([[ 2.,  8.,  0.,  6.],
       [ 4.,  5.,  1.,  1.],
       [ 8.,  9.,  3.,  6.]])
a

array([[2., 8., 0., 6.],
       [4., 5., 1., 1.],
       [8., 9., 3., 6.]])

In [23]:
a.reshape((4, 3))

array([[2., 8., 0.],
       [6., 4., 5.],
       [1., 1., 8.],
       [9., 3., 6.]])

In [26]:
a = np.arange(6)
b = a
b[0] = 10
a

array([10,  1,  2,  3,  4,  5])

In [29]:
a = a.reshape((2,3))
a

array([[10,  1,  2],
       [ 3,  4,  5]])

In [31]:
s = a[0:2, 1:3]
s

array([[1, 2],
       [4, 5]])

In [32]:
s[1, 1] = 100
s

array([[  1,   2],
       [  4, 100]])

In [33]:
a

array([[ 10,   1,   2],
       [  3,   4, 100]])

In [34]:
s is a

False

In [35]:
s.base is a

False

In [37]:
# Fancy indexing
a = np.arange(12)**2
a[[0, 2, 4]]

array([ 0,  4, 16], dtype=int32)

In [39]:
a[[False, False, False, False, False,  True,  True,  True, True,  True,  True,  True]]

array([ 25,  36,  49,  64,  81, 100, 121], dtype=int32)