In [1]:
import numpy as np

In [3]:
numbers = [2, 3, 5, 7]  # list
a = np.array(numbers)

In [12]:
a, a.dtype, a.itemsize

(array([2, 3, 5, 7]), dtype('int32'), 4)

In [8]:
matrix = [numbers, [22, 33, 55, 77]]
b = np.array(matrix)

In [13]:
b, b.dtype, b.itemsize

(array([[ 2,  3,  5,  7],
        [22, 33, 55, 77]]), dtype('int32'), 4)

In [14]:
matrix = [numbers, [22, 33, 55, 77]]
c = np.array(matrix, dtype=np.int64)

In [16]:
c, c.dtype, c.itemsize

(array([[ 2,  3,  5,  7],
        [22, 33, 55, 77]], dtype=int64), dtype('int64'), 8)

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones(4, dtype=np.int16)

array([1, 1, 1, 1], dtype=int16)

In [24]:
np.ones((2, 2), dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

In [25]:
np.empty(3)

array([4.05e-322, 0.00e+000, 0.00e+000])

In [29]:
d = np.arange(6)
d

array([0, 1, 2, 3, 4, 5])

In [30]:
e = d.reshape(2, 3)
e

array([[0, 1, 2],
       [3, 4, 5]])

In [31]:
a = np.arange(1, 10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
b = np.arange(101, 110)
b

array([101, 102, 103, 104, 105, 106, 107, 108, 109])

In [37]:
a * b

array([101, 204, 309, 416, 525, 636, 749, 864, 981])

In [39]:
a + 50

array([51, 52, 53, 54, 55, 56, 57, 58, 59])

In [40]:
a < b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [42]:
a < 5

array([ True,  True,  True,  True, False, False, False, False, False])

In [43]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [44]:
a * b

array([[ 5, 12],
       [21, 32]])

In [45]:
a @ b

array([[19, 22],
       [43, 50]])

In [46]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [47]:
a = a + 10
a

array([11, 12, 13, 14, 15])

In [50]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
a.sum()

21

In [52]:
a.sum(axis=0)

array([5, 7, 9])

In [53]:
a.sum(axis=1)

array([ 6, 15])

In [54]:
a.mean()

3.5

In [55]:
a.mean(axis=1)

array([2., 5.])